### ISSUE TITLE
Add PRIME to MT sota

### ISSUE THREAD

**Issue by TobiasLee** [ZNLP/SOTA-MT#1]
According to [NLP Progress](http://nlpprogress.com/english/machine_translation.html), PRIME( originally called MUSE) achieves 29.9 on En-De dataset. 
Paper: [MUSE: Parallel Multi-Scale Attention for Sequence to Sequence Learning](https://arxiv.org/abs/1911.09483)
Code:  https://github.com/lancopku/MUSE

**Comment by jiajunzhangnlp** [comment]
> According to [NLP Progress](http://nlpprogress.com/english/machine_translation.html), PRIME( originally called MUSE) achieves 29.9 on En-De dataset.
> Paper: [MUSE: Parallel Multi-Scale Attention for Sequence to Sequence Learning](https://arxiv.org/abs/1911.09483)
> Code: https://github.com/lancopku/MUSE

Thanks for pointing out this paper and the performance is very good. We will add it. Maybe it is better to provide the parameter details during comparison in the experiments table.
